### ISSUE TITLE
Interactive installs get blocked by waiting for service

### ISSUE THREAD

**Issue by discentem** [google/cabbie#88]
Running `.\cabbie -debug install -all` appears to wait for the default update interval. I'd expect the update to start immediately for an interactive run. 

<img width="1007" alt="Screen Shot 2021-12-11 at 2 34 57 PM" src="https://user-images.githubusercontent.com/2560432/145865116-85a1c758-56cf-423f-8950-05d8adb52171.png">

Curiously, if it ctrl+c on the keyboard, Cabbie stops the service and proceeds immediately. 
<img width="1023" alt="Screen Shot 2021-12-11 at 2 35 17 PM" src="https://user-images.githubusercontent.com/2560432/145865930-91da7e8c-e70d-496c-bb30-71bbdce9bb2f.png">

**Comment by TsekNet** [comment]
Without looking through the code, my assumption is that this is due to the use of [time.Ticker](https://github.com/google/cabbie/blob/e9a27136d417dd6cbd2e1fd21114ea903369510e/cabbie.go#L83).

time.Ticker does *not* tick immediately, but instead waits the default interval, see the Go devs comment on this issue: https://github.com/golang/go/issues/17601.

There are multiple ways to work around this, but the easiest is generally to force an initial tick, by calling a function, before the use of the ticker.

**Comment by discentem** [comment]
Hey @TsekNet, my intention was actually to just get Cabbie to print info logs to stdout during interactive runs. After reviewing the code base, `-debug` does not seem like the correct way to do this. 

Thus I submitted this PR https://github.com/google/cabbie/pull/92. If you have time, please review and let me know what you think 😄

**Comment by discentem** [comment]
fwiw: I dropped #92 in favor of #94
